services:
  patrones-db:
    image: postgres:latest
    container_name: patrones-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./parte_1:/mnt/data 
  adminer:
    image: adminer
    ports:
      - "8080:8080"
